### ISSUE TITLE
Nothing shows up 

### ISSUE THREAD

**Issue by hoodelali** [BlenderDefender/Blender-Analytics#1]
**Describe the bug**
After a proper new installation of blender 2.91, I download the addon from blender market, install it in blender, check the activating box, but nothing appear on N > View.

**To Reproduce**
previously described, see screenshot below

**Expected behavior**
Anything 

**Screenshots**
https://i.imgur.com/49H7jLF.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Blender Version, tried on 2.83, 2.90 and 2.91, same issue

**Comment by BlenderDefender** [comment]
You have to enter the license key you should have received per E-Mail. Then, restart Blender and eberything should work just fine.
